name: cis_driver_app
description: "Concept Illustrated Services - Driver Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  hugeicons: ^1.1.1
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  firebase_database: ^12.0.4
  
  # Navigation
  go_router: ^17.0.0
  
  # Maps & Location
  mapbox_maps_flutter: ^2.12.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Image & Media
  image_picker: ^1.1.2
  signature: ^6.3.0
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.3.2
  http: ^1.2.0
  
  # Swipe Actions
  flutter_slidable: ^4.0.3
  
  # UI Components
  flutter_svg: ^2.0.10+1
  
  # Charts
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^3.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - .env
    # Uncomment below when you add image assets
    # - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
